//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryCo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string ProductCode { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool PromotionApplied { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
