//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryCo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Promotions = new HashSet<Promotion>();
        }
    
        public string Code { get; set; }
        public string ProductTypeCode { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
