//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryCo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public long Id { get; set; }
        public string ProductCode { get; set; }
        public string PromotionCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ApplyTo { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PromotionType PromotionType { get; set; }
    }
}
